// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-l3R5XaVY-vWnSgCTQ7KzZLtU5Icpzc',
    appId: '1:86914973774:web:7c491c04c50cbd0798031f',
    messagingSenderId: '86914973774',
    projectId: 'plant-app-firebase',
    authDomain: 'plant-app-firebase.firebaseapp.com',
    storageBucket: 'plant-app-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB6Ey-H7Yok8JNoawurys17JrjJWKfBRE',
    appId: '1:86914973774:android:7e2f4f0a850a6f5098031f',
    messagingSenderId: '86914973774',
    projectId: 'plant-app-firebase',
    storageBucket: 'plant-app-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPBA_tFj0pbOm5Tn4Oe12NJAoo5WCRso',
    appId: '1:86914973774:ios:5e28f556326bfa3898031f',
    messagingSenderId: '86914973774',
    projectId: 'plant-app-firebase',
    storageBucket: 'plant-app-firebase.appspot.com',
    iosClientId: '86914973774-g0b42klm5bdjjga35ftn3iqp6168as3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPBA_tFj0pbOm5Tn4Oe12NJAoo5WCRso',
    appId: '1:86914973774:ios:5e28f556326bfa3898031f',
    messagingSenderId: '86914973774',
    projectId: 'plant-app-firebase',
    storageBucket: 'plant-app-firebase.appspot.com',
    iosClientId: '86914973774-g0b42klm5bdjjga35ftn3iqp6168as3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantApp',
  );
}
